trigger:
- main

pool:
   name: ubuntu

variables:
  group: var-aks
  namespace: dev 
  chartpath: ./hospital

stages:
  - stage: Deploy
    displayName: Deploying Microservices to Minikube Cluster
    
    jobs:
    - job: HelmDeploy
      displayName: Helm Deployment