trigger:
- main

pool:
   name: ubuntu

variables:
  group: var-aks
  namespace: dev 
  chartpath: ./hospital

stages:
  - stage: Deploy
    displayName: Deploying Microservices to Minikube Cluster
    
    jobs:
    - job: HelmDeploy
      displayName: Helm Deployment

      steps:
        - checkout: self

        - script: |
            echo "checking K8S Connection.."
            kubectl get nodes
          displayName: check cluster
        
        - script: |
           echo "creating namespace if it does not exist"
           kubectl create namespace $(namespace) --dry-run=client -o yaml | kubectl apply -f -
          displayName: Creating namespace

        - script: |
            kubectl apply -f $(chartpath)/mysql.yaml -n $(namespace)
          displayName: Deploy MySQL

        - script: |
             kubectl rollout status deployment/mysql -n $(namespace) --timeout=180s
          displayName: Wait for MySQL

        - script: |
            echo "Deploying Frontend Service"
            helm upgrade --install frontend $(chartpath) \
            -f $(chartpath)/values-front.yaml
            -n $(namespace)
          displayName: Deploy frontend
        - script: |
            echo "Deploying patient service"
            helm upgrade --install patient $(chartpath) \
            -f $(chartPath)/values-patient.yaml \
            -n $(namespace)
          displayName: Deploy patient

        - script: |
            echo "Deploying appointment service"
            helm upgrade --install appointment $(chartpath) \
            -f $(chartPath)/values-appointment.yaml \
            -n $(namespace)
          displayName: Deploy appointment

        - script: |
            echo "Checking Helm releases"
            helm list -n $(namespace)
            echo "Checking Pods"
            kubectl get pods -n $(namespace)
            echo "Checking Services"
            kubectl get svc -n $(namespace)
          displayName: Verify deployment