trigger:
  - main

pool:
  name: Default

variables:
  - group: my-var

stages:
 
- stage: docker_build
  displayName: Build & Push Docker Images
  jobs:
  - job: build
    displayName: Docker Build
    steps:
    - checkout: self
 
    - task: Docker@2
      displayName: Build & Push Frontend
      inputs:
        containerRegistry: DockerHubServiceConnection
        repository: chiedo95/frontend-api:latest
        command: buildAndPush
        dockerfile: hospital-frontend/Dockerfile
        buildContext: hospital-frontend
        tags: |
          $(Build.BuildId)
           latest
 
    - task: Docker@2
      displayName: Build & Push Patient API
      inputs:
        containerRegistry: DockerHubServiceConnection
        repository: chiedo95/patient-api:latest
        command: buildAndPush
        dockerfile: patient-api/Dockerfile
        buildContext: patient-api
        tags: |
          $(Build.BuildId)
           latest
 
    - task: Docker@2
      displayName: Build & Push Appointment API
      inputs:
        containerRegistry: DockerHubServiceConnection
        repository: chiedo95/appointment-api:latest
        command: buildAndPush
        dockerfile: appointment-api/Dockerfile
        buildContext: appointment-api
        tags: |
          $(Build.BuildId)
           latest
 

    - script: |
        kubectl apply -n hospital -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mysql
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: mysql
          template:
            metadata:
              labels:
                app: mysql
            spec:
              containers:
              - name: mysql
                image: mysql:8.0
                env:
                - name: MYSQL_ROOT_PASSWORD
                  value: pass123
                - name: MYSQL_DATABASE
                  value: hospital
                - name: MYSQL_USER
                  value: user
                - name: MYSQL_PASSWORD
                  value: pass123
                ports:
                - containerPort: 3306
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: mysql
        spec:
          selector:
            app: mysql
          ports:
          - port: 3306
            targetPort: 3306
        EOF
      displayName: Deploy MySQL (Official)
 