trigger:
  - main

pool:
  name: Default

variables:
  - group: my-var

stages:
    - stage: docker_build
      displayName:  Build and Push Docker Images
      jobs:
          - job: Build
